To-do-list App
ifeanyi305/To-do-list-App pull request #2
Opened 2022-11-03 16:24 UTC by ifeanyi305

I added the CRUD method to my to-do list project.
The Add and Remove button is active
The added task can be updated 
The to-do list was built with HTML, js, CSS, and webpack
linters errors are fixed

2022-11-03 20:28 UTC, aimalamiri requested changes
Hi @ifeanyi305, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![AlmostThereReachGIF](https://user-images.githubusercontent.com/34779928/191347504-9f70659c-a01f-48a1-ad46-b8722d46ffca.gif)

## Highlights

- The app is designed very well and look fantastic ✔️ ⭐
- Good job for using the right GitHub Flow 💯
- Awesome file organization 🗃️
- Commits are descriptive and meaningful 👍
- Linters are properly set up and passing 🟢 👍

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-03 20:28 UTC, aimalamiri commented on src/index.js
> +// })
It's highly recommended to remove the commented code from your project, please make sure to keep your repository as clean as possible.

2022-11-03 20:28 UTC, aimalamiri commented on src/modules/app.js
> +        <input class='item' id='check-${id}', "completed")' type='checkbox' ${item.Checked ? 'true' : 'false'} onclick='updateList(${id}, "completed")'>
Good job! but it has a small issue, when I click on the checkbox it does complete the task, but when I refresh the page the checkbox does not remain checked. Please make sure to `check` the checkbox for completed tasks.

2022-11-03 20:28 UTC, aimalamiri commented on src/modules/app.js
> +};
It works great, but it's part of the project requirement to update the index property for all of the tasks when you remove a task.

![image](https://user-images.githubusercontent.com/34779928/199826694-762a1a4a-55a5-4844-bc05-4322a4b61586.png)

2022-11-03 20:28 UTC, aimalamiri commented on src/modules/app.js
> +    }
Good job! but it's required to update the localStorage when you update the task description. This helps to persist the data. Please make sure to fix this.

2022-11-04 10:51 UTC, Kamba56 commented on src/modules/app.js
> +        <input class='item' id='check-${id}', "completed")' type='checkbox' ${item.Checked ? 'true' : 'false'} onclick='updateList(${id}, "completed")'>
Hi @aimalamiri, I think this functionality is for the next milestone (interactive list). This is the add remove milestone.

2022-11-04 11:02 UTC, Kamba56 approved these changes
Hi @ifeanyi305, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏
## Highlights
- [x] All linters passed!👏👏👏
- [x] Great use of Github workflow!👏👏👏
- [x] Descriptive PR!👏👏👏

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-04 11:02 UTC, Kamba56 commented on src/index.html
>              </div>
- [Optional] Consider using an indentation of two spaces in all your documents. This is a convention and also [best practice.](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md)

2022-11-04 19:21 UTC, merged

2022-12-17 02:44 UTC, ifeanyi305 commented on src/index.html
>              </div>
Thank you